// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Check if real Supabase credentials are configured
const hasRealCredentials = () => {
  return SUPABASE_URL.includes('supabase.co') && 
         !SUPABASE_URL.includes('placeholder') &&
         SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key' &&
         !SUPABASE_PUBLISHABLE_KEY.includes('placeholder');
};

export const isSupabaseConfigured = hasRealCredentials();

// Create client only if real credentials exist
export const supabase: SupabaseClient<Database> | null = hasRealCredentials()
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;